/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/messages/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release messages
         * @description Forwards the given messages to the configured SMTP server, optionally overriding the from and to addresses.
         */
        post: operations["releaseMessages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete messages
         * @description Permanently removes the given messages.
         */
        post: operations["deleteMessages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one message
         * @description Returns a single message in full, including its text body.
         */
        get: operations["getMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List captured messages
         * @description Returns one page of message summaries. Each summary omits the message body; use getMessage for that. Sort by receivedTimestamp, from, to or subject. Every filter is optional, matching on a case-insensitive substring, and they are combined with AND. receivedFrom and receivedTo are inclusive ISO-8601 instants bounding when the mail arrived. The total reflects the filter, not the whole mailbox.
         */
        get: operations["getTableData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MessageReleaseRequest: {
            messageIds?: number[];
            overrideTo?: boolean;
            overrideToAddresses?: string;
            overrideFrom?: boolean;
            overrideFromAddress?: string;
        };
        MessageReleaseOutcome: {
            /** Format: int64 */
            id?: number;
            released?: boolean;
            errorMessage?: string;
        };
        MessageReleaseResponse: {
            successful?: boolean;
            errorMessage?: string;
            outcomes?: components["schemas"]["MessageReleaseOutcome"][];
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        MessageDeleteRequest: {
            messageIds?: number[];
        };
        MessageResponse: {
            successful?: boolean;
            errorMessage?: string;
        };
        MessageDetail: {
            /** Format: int64 */
            id?: number;
            from?: string;
            to?: string;
            /** Format: date-time */
            receivedTimestamp?: string;
            /** Format: date-time */
            releasedTimestamp?: string;
            subject?: string;
            body?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        MessageSummary: {
            /** Format: int64 */
            id?: number;
            from?: string;
            to?: string;
            /** Format: date-time */
            receivedTimestamp?: string;
            /** Format: date-time */
            releasedTimestamp?: string;
            /** Format: int64 */
            sizeBytes?: number;
            subject?: string;
        };
        PageResponse: {
            content?: components["schemas"]["MessageSummary"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    releaseMessages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageReleaseRequest"];
            };
        };
        responses: {
            /** @description An outcome per requested id, in the order requested. Delivery is not reversible, so a batch can partly succeed: successful is true only when every id was released, and the per-id outcomes are what to consult before retrying, since retrying the whole batch re-sends what already went out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageReleaseResponse"];
                };
            };
            /** @description The body named no messages to release: messageIds was absent, misspelled, null or empty. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    deleteMessages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageDeleteRequest"];
            };
        };
        responses: {
            /** @description Per-id outcome. This reports failures in the body rather than with a status code, so a partially successful request is still a 200. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description The body named no messages to delete: messageIds was absent, misspelled, null or empty. Rejected rather than reported as a successful no-op, because deleting nothing while claiming success reads as though the messages are gone. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The message, in full. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetail"];
                };
            };
            /** @description The id is not a number. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No message has that id. It may have been deleted, or the id may never have existed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getTableData: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
                subject?: string;
                from?: string;
                to?: string;
                receivedFrom?: string;
                receivedTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matching messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description A parameter could not be understood: a sort field other than the four above, a filter timestamp that is not an ISO-8601 instant, or a page or size outside the accepted range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
